[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --workers 1 --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
